language: 
- node_js
node_js:
- node
before_script:
- 'curl -H ''Cache-Control: no-cache'' https://raw.githubusercontent.com/fossas/fossa-cli/master/install.sh
  | sudo bash'
after_success:
- npm run coverage
- fossa init
- fossa analyze
deploy:
  provider: npm
  edge: true
  api_token:
    secure: c8iIzVsSUmAh7qGgMmEVWYH1ldAlDZFq0xhz5WFlAL9DUwj/n7X0kq5p9yDn+/z7DV+Ys1+mZolyPEOFXqB2dmaFEAYTiLHi+YZ7s6OCOhxC7MKDn7aPU4WM8fSxw48vssGStipWQX7VJqnwZG+TZ+q1ntRSPWLaVFZkwDecQ9iy1bVfh2G17JQYAmqNd8CgSlaBKUUQ3nSntRWfTil/NunEUs8luCmsUh6THyMsIWOhTx7aMaUX56l9NtVMFWA3EQSKD5gaXvbr9FX9oPPvKHBO6X5+Bwtto20q7ctCcTuTVD3JNHAvyxarjPEZOyO3a9WnMeOcjdeyYvYGxo4dxoxBRtChLtZQ4tfjj//WNafGhfhQtAtYsvnCsQZwdZcFDYV1wbKYmUKSO7bgsh+ttVB1h4C4ZJAL1dvN8ofhA/aHPoNWI0rTSeM7jbM4ILbt4833DIkTnN5c+AUr47WnGzsXXTjQcqZLCE+8OdwPpyNeX/4AJkK8ErD1Os11GtdR4TiB88CfoSHxOPE6Q41Nz4Y6cN96gwetQvSUhlUpylQ6MMUIy1k23kUk+VBgCSBLEIwKmy+HrRw8lPZhBApmTCAOrAzvFcUQZcSs0GPn2Fn2V6NDsw3sdB8W4aJL1HqM2+z62r+L2TPnqJ3+iA0xE7QMQhet70LbYWVOWv4VGdE=
