version: 1
update_configs:
- package_manager: "javascript"
  directory: "/"
  update_schedule: "monthly"
  default_labels:
  - "dependencies"
  - "dependabot"
  allowed_updates:
    - match:
        update_type: "all"
  automerged_updates:
    - match:
        dependency_type: "all"
        update_type: "all"
  version_requirement_updates: "auto"
  commit_message:
    prefix: "chore"
    prefix_development: "no-release"
    include_scope: true
